### ISSUE TITLE
finish implementing model for `MessagePayload`

### ISSUE THREAD

**Issue by grottohub** [grottohub/glyph#3]
right now, the library only supports the `content` field when sending a message. this is probably the most important model to finish fleshing out as it provides richer options for structuring your message.

see the model [here](https://github.com/grottohub/glyph/blob/2b700b673af8acc86bec04e2716636ee6c051c40/src/glyph/models/discord.gleam#L96), and the Discord docs [here](https://discord.com/developers/docs/resources/channel#create-message).

as with previous models, make sure to fully define the types used by a `MessagePayload` (such as also creating an [`Embed`](https://discord.com/developers/docs/resources/channel#embed-object) model).

important: since this is a payload, it does not need a decoder, but it _does_ need an encoder (from model to json)

**Comment by teesh3rt** [comment]
thank you (im jan pona)

**Comment by tygore587** [comment]
Hi, i wanted to get into gleam a bit but i'm totally new in this space. I normally use dotnet for everything.

Do I need anything as a headstart before starting on this issue or what would you recommend to look at before starting? 
I just wanted to take their tour beforehand.

**Comment by grottohub** [comment]
hey @tygore587 👋🏻  if you're entirely new to gleam, definitely run through the [tour](https://tour.gleam.run/). this issue will primarily cover the concept of [records](https://tour.gleam.run/data-types/records/).

encoding is fairly straightforward (matching the proper field to it's relevant data structure and value), but there may be some gotchas for nested fields, non-trivial types, etc. so definitely feel free to ask questions!
